---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
html

tables <- html %>% html_table(fill=TRUE)
tables %>% str()

hof2023 <- tables[[1]]

library(Lahman)
View(HallOfFame)
View(People)
```

```{r}
# Remove columns 13-39 from 2023 data
hof2023 <- hof2023[, -c(13:39)]

# Set the first row as column headers
colnames(hof2023) <- as.character(hof2023[1, ])

# Remove the first row
hof2023 <- hof2023[-1, ]

# Remove the first column
hof2023 <- hof2023[, -1]

# Add 'inducted' column based on condition of at least 292 votes
hof2023$inducted <- ifelse(hof2023$Votes >= 292, "Y", "N")

# Add 'yearID' column with every entry as 2023
hof2023$yearID <- 2023

# Create a single 'Name' column for the 'People' data set
People$Name <- paste(People$nameFirst, People$nameLast, sep = " ")

# Get the index of the 'Name' column
name_index <- which(names(People) == "Name")

# Move the 'Name' column to the first position
People <- People[, c(name_index, setdiff(1:ncol(People), name_index))]

```

```{r}
# Merge 'HallOfFame' with 'People' based on 'playerID' to bring in the 'Name' column
HallOfFame_People <- merge(HallOfFame, People[, c("playerID", "Name")], by = "playerID", all.x = TRUE)

#Merge 'hof2023' with 'People' based on 'Name' to bring in the 'playerID' column
hof2023_People <- merge(hof2023, People[, c("Name", "playerID")], by = "Name", all.x = TRUE)

# Missing playerID values and corresponding Name values
missing_values <- c("beltrca01", "rodrifr03", "heltoto01", "ethiean01", "arroybr01", "streehu01", "hardyjj01", "ellsbja01", "werthja01", "kentje01", "weaveje02", "peraljh01", "lackejo01", "cainma01", "napolmi01", "dickera01")
corresponding_names <- c("Carlos Beltrán", "Francisco Rodríguez", "Todd Helton HOF", "X-Andre Ethier", "X-Bronson Arroyo", "X-Huston Street", "X-J.J. Hardy", "X-Jacoby Ellsbury", "X-Jayson Werth", "X-Jeff Kent", "X-Jered Weaver", "X-Jhonny Peralta", 
"X-John Lackey", "X-Matt Cain", "X-Mike Napoli", "X-R.A. Dickey")

# Add missing playerID values
for (i in seq_along(missing_values)) {
  hof2023_People$playerID[hof2023_People$Name == corresponding_names[i]] <- missing_values[i]
}

```

```{r}
# Convert 'Votes' column to numeric type
hof2023_People$Votes <- as.numeric(hof2023_People$Votes)

# Convert 'inducted' column to factor type
hof2023_People$inducted <- as.factor(hof2023_People$inducted)

# Rename the 'votes' column to 'Votes'
names(HallOfFame_People)[names(HallOfFame_People) == "votes"] <- "Votes"


```

```{r}
library(dplyr)

hof2023_People <- hof2023_People %>% mutate(
  yearID = 2023,
  votedBy = "BBWAA",
  ballots = 389,
  needed = 292,
  inducted = ifelse(Votes>=292, "Y", "N"),
  category = NA, # don't know yet
  needed_note = NA # not sure what would go here
) %>% rename(
  Votes = Votes
)
```

```{r}
# Remove desired columns
hof2023_People <- hof2023_People %>% select(-'YoB', -'%vote', -'HOFm', -'HOFs', -'Yrs', -'WAR', -'WAR7', -'JAWS', -'Jpos')

hof2023_People <- hof2023_People %>% select(-'Name')

# Reorder columns based on the specified order
hof2023_People <- hof2023_People[, c("playerID", "yearID", "votedBy", "ballots", "needed", "Votes", "inducted", "category", "needed_note")]

hof2023_People <- hof2023_People %>%
                   rename(votes = Votes)
```

```{r}
HallOfFame_Updated <- rbind(HallOfFame, hof2023_People)
```

